### ISSUE TITLE
invalid IP addresses

### ISSUE THREAD

**Issue by XStreamke** [securityscorecard/SSC-Threat-Intel-IoCs#1]
Dear,

The following are invalid IP addresses (with port number): 
103.250.166.04:6667 -> 103.250.166.4:6667 ?
074.205.128.200:8010 -> 74.205.128.200:8010
035.86.232.240:8021 -> 35.86.232.240:8021
047.98.219.185:8999 -> 47.98.219.185:8999
034.66.5.144:8888 -> 34.66.5.144:8888
03.138.31.205:8080 -> 3.138.31.205:8080
01.222.45.2:9992 -> 1.222.45.2:9992
03.202.255.67:8080 -> 3.202.255.67:8080
01.222.45.0:9992 -> 1.222.45.0:9992
00.106.184.21:9991 -> 0.106.184.21:9991? (reserved IP (can be software))
047.91.22.18:8084 -> 47.91.22.18:8084
045.154.58.173:7686 -> 45.154.58.173:7686
013.125.146.68:8045 -> 13.125.146.68:8045
020.205.61.143:8123 -> 20.205.61.143:8123
047.241.122.19:8010 -> 47.241.122.19:8010

I also noticed private IP address ranges, which isn't a good practice, because it could potentially block internal IP ranges on company networks.
Ranges starting from 10.x.x.x are considered private... And those starting with 0.x.x.x are reserved for software...
Examples:
10.16.44.9:8888
0.61.88.147:8080
0.109.32.28:8045
0.82.40.43:8080
0.164.15.182:8080

Apart from that, great work!

Regards,
Kevin

**Comment by m0ndzon3** [comment]
Thanks for pointing this out.  We have added new filters to skip reserved/private IP addresses and also fixed the invalid IP addresses.
